-- 321 Football Challenge — Friend Match schema
-- Run this once in the Supabase SQL editor (Dashboard → SQL Editor → New query).
--
-- Design notes
-- ------------
-- ONE ROW PER ROOM holds the entire match. Both clients subscribe to that row
-- and derive their whole screen from it; neither phone ever tells the other
-- what to do. That makes reconnection trivial (re-read the row) and removes
-- any need for server-side game code — which matters, because there is none:
-- no Edge Functions, no triggers that decide anything. The round winner is
-- decided by comparing two elapsed-time numbers, and both clients can do that
-- arithmetic themselves and reach the same answer.
--
-- TIMES ARE SERVER TIMES. pick_deadline / unlock_at / answer_deadline are
-- written as `now() + interval`, evaluated by Postgres, so both clients read
-- the same instant. Each client converts to its own clock using the offset it
-- measures against server_now(). Do not have a client write its own
-- DateTime.now() into these columns — that is the drift this design exists to
-- avoid.

-- ---------------------------------------------------------------------------
-- rooms
-- ---------------------------------------------------------------------------
create table if not exists public.rooms (
  code              text primary key check (code ~ '^[0-9]{6}$'),
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),

  -- Players. Ids are generated by the client; see the RLS note at the bottom.
  host_id           uuid        not null,
  host_name         text        not null,
  guest_id          uuid,
  guest_name        text,

  -- Match settings, per room so they can be tuned without a deploy.
  target_goals      int         not null default 3,
  pick_seconds      int         not null default 15,
  countdown_seconds int         not null default 3,
  answer_seconds    int         not null default 10,

  -- Match state.
  -- phase: lobby | picking | countdown | answering | round_over | match_over
  phase             text        not null default 'lobby',
  round             int         not null default 0,
  host_score        int         not null default 0,
  guest_score       int         not null default 0,

  -- The round in progress.
  host_club_id      int,
  host_club_name    text,
  guest_club_id     int,
  guest_club_name   text,
  pick_deadline     timestamptz,
  unlock_at         timestamptz,   -- when the 3-2-1 ends and input opens
  answer_deadline   timestamptz,

  -- Submissions. elapsed_ms is measured by each client with a MONOTONIC clock
  -- (Dart's Stopwatch) from its own unlock instant, and stamped when GÖNDER is
  -- pressed — not when validation returns, which would penalise a slower phone
  -- for its own database lookup. Comparing two durations rather than two wall
  -- clocks is what makes NTP drift between the phones cancel out.
  host_answer       text,
  host_elapsed_ms   int,
  guest_answer      text,
  guest_elapsed_ms  int,

  -- Round outcome. round_winner is null on a void round.
  round_winner      text,          -- host | guest
  round_reason      text,          -- correct | no_answer | unplayable

  -- Match outcome.
  winner            text,          -- host | guest
  ended_reason      text,          -- goals | forfeit_host | forfeit_guest

  -- Liveness. Each client touches its own column; the opponent treats a stale
  -- value as a disconnect and claims the match.
  host_seen_at      timestamptz,
  guest_seen_at     timestamptz,

  constraint rooms_phase_valid check (
    phase in ('lobby','picking','countdown','answering','round_over','match_over')
  )
);

create index if not exists idx_rooms_created_at on public.rooms (created_at);

-- Realtime sends only the primary key on an UPDATE unless the table replicates
-- its full row. Without this, clients receive `{code: "123456"}` and nothing
-- else, and the match appears to freeze.
alter table public.rooms replica identity full;

-- updated_at is maintained here rather than trusted from the client, so a
-- stale write cannot appear newer than a fresh one.
create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists rooms_touch_updated_at on public.rooms;
create trigger rooms_touch_updated_at
  before update on public.rooms
  for each row execute function public.touch_updated_at();

-- ---------------------------------------------------------------------------
-- server_now() — the clock the countdown is anchored to
-- ---------------------------------------------------------------------------
-- Firebase's Realtime Database ships `.info/serverTimeOffset` for exactly this
-- job; Supabase has no equivalent, so the client measures it NTP-style: call
-- this a handful of times, and for each call compute
--     offset = server_ms - (sent_ms + received_ms) / 2
-- keeping the sample with the smallest round trip. clock_timestamp() is used
-- rather than now() because now() returns the transaction start time, which is
-- constant within a statement and would quantise the measurement.
create or replace function public.server_now()
returns bigint
language sql
stable
as $$
  select (extract(epoch from clock_timestamp()) * 1000)::bigint;
$$;

-- ---------------------------------------------------------------------------
-- create_room() — a 6-digit code that is free at the moment it is taken
-- ---------------------------------------------------------------------------
-- Generating a code client-side and hoping means two friends can be handed the
-- same code. Inserting inside a retry loop means the primary key itself
-- settles it: whoever commits first owns the code, the loser tries another.
create or replace function public.create_room(
  p_host_id   uuid,
  p_host_name text
)
returns public.rooms
language plpgsql
security definer
set search_path = public
as $$
declare
  v_code text;
  v_room public.rooms;
begin
  for i in 1..20 loop
    v_code := lpad((floor(random() * 1000000))::int::text, 6, '0');
    begin
      insert into public.rooms (code, host_id, host_name, host_seen_at)
      values (v_code, p_host_id, p_host_name, now())
      returning * into v_room;
      return v_room;
    exception when unique_violation then
      -- taken between the pick and the insert; go round again
    end;
  end loop;
  raise exception 'could not allocate a free room code after 20 attempts';
end;
$$;

-- ---------------------------------------------------------------------------
-- join_room() — fill the guest seat, once
-- ---------------------------------------------------------------------------
-- The `guest_id is null` predicate is the whole point: it makes claiming the
-- seat a single atomic UPDATE, so a third player racing a second one loses
-- rather than silently overwriting them.
create or replace function public.join_room(
  p_code       text,
  p_guest_id   uuid,
  p_guest_name text
)
returns public.rooms
language plpgsql
security definer
set search_path = public
as $$
declare
  v_room public.rooms;
begin
  update public.rooms
     set guest_id = p_guest_id,
         guest_name = p_guest_name,
         guest_seen_at = now()
   where code = p_code
     and phase = 'lobby'
     and (guest_id is null or guest_id = p_guest_id)
  returning * into v_room;

  if v_room.code is null then
    -- Distinguish the three ways this fails, so the UI can say which.
    if not exists (select 1 from public.rooms where code = p_code) then
      raise exception 'room_not_found';
    elsif exists (select 1 from public.rooms where code = p_code and phase <> 'lobby') then
      raise exception 'room_in_progress';
    else
      raise exception 'room_full';
    end if;
  end if;

  return v_room;
end;
$$;

-- ---------------------------------------------------------------------------
-- purge_stale_rooms() — housekeeping
-- ---------------------------------------------------------------------------
-- A friend match lasts minutes. Anything older than a day is abandoned, and
-- the free tier's 500 MB is not worth spending on it. Call it from the client
-- occasionally, or schedule it with pg_cron if that extension is enabled.
create or replace function public.purge_stale_rooms()
returns int
language sql
security definer
set search_path = public
as $$
  with gone as (
    delete from public.rooms
     where created_at < now() - interval '1 day'
    returning 1
  )
  select count(*)::int from gone;
$$;

-- ---------------------------------------------------------------------------
-- Row level security
-- ---------------------------------------------------------------------------
-- BE CLEAR ABOUT WHAT THIS DOES AND DOES NOT DO.
--
-- These policies let any holder of the anon key read and write any room row.
-- That is a deliberate match for the project's standing decision not to write
-- anti-cheat: the players are two friends sharing a code, and there is no
-- ranked economy to exploit. What RLS is doing here is keeping the surface
-- explicit and narrow — only this table, only these operations, no deletes.
--
-- It is NOT protecting a room from someone who guesses its six digits, and it
-- does not stop a determined player editing the score. If that ever matters,
-- the upgrade is Supabase anonymous sign-ins (free, and well inside the 50k
-- MAU allowance): turn them on, then narrow each policy's `using` clause to
--     auth.uid() in (host_id, guest_id)
-- and have the client sign in anonymously before creating or joining.
alter table public.rooms enable row level security;

drop policy if exists rooms_read on public.rooms;
create policy rooms_read on public.rooms
  for select to anon, authenticated using (true);

drop policy if exists rooms_insert on public.rooms;
create policy rooms_insert on public.rooms
  for insert to anon, authenticated with check (true);

drop policy if exists rooms_update on public.rooms;
create policy rooms_update on public.rooms
  for update to anon, authenticated using (true) with check (true);

-- No delete policy: rooms go only through purge_stale_rooms(), which is
-- security definer and therefore not reachable as a plain table delete.

-- GRANTS ARE NOT OPTIONAL, AND POLICIES DO NOT IMPLY THEM.
-- Postgres checks privileges first and RLS second, so without these every
-- direct read or write of the table fails with `42501 permission denied for
-- table rooms` no matter how permissive the policies above are. Supabase adds
-- these automatically for tables created in the dashboard's table editor, but
-- not for a table created from raw SQL — which is how this one was made, and
-- the RPCs masked it because SECURITY DEFINER functions run as their owner.
-- Delete is withheld on purpose; see the note above.
grant select, insert, update on public.rooms to anon, authenticated;

grant execute on function public.server_now()              to anon, authenticated;
grant execute on function public.create_room(uuid,text)    to anon, authenticated;
grant execute on function public.join_room(text,uuid,text) to anon, authenticated;
grant execute on function public.purge_stale_rooms()       to anon, authenticated;

-- ---------------------------------------------------------------------------
-- Realtime
-- ---------------------------------------------------------------------------
-- Publishes row changes so both clients can subscribe to their room.
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
     where pubname = 'supabase_realtime'
       and schemaname = 'public'
       and tablename = 'rooms'
  ) then
    alter publication supabase_realtime add table public.rooms;
  end if;
end;
$$;
