import re
a, b, c = User(conn), User(conn), User(conn)
p = a.one("select * from create_profile('Yaman')")
ok("profile created", p["id"] == a.id and p["coins"] == 30 and p["trophies"] == 0)
ok("tag alphabet", re.fullmatch(r"[A-HJ-NP-Z2-9]{4}", p["tag"]), p["tag"])
ok("idempotent", a.one("select * from create_profile('Other')")["tag"] == p["tag"])
ok("short name refused", b.fails("select create_profile('ab')"))
ok("space refused", b.fails("select create_profile('a b c')"))
ok("turkish ok", b.one("select * from create_profile('Şükrü_10')")["username"] == "Şükrü_10")
c.one("select * from create_profile('Yaman')")
ok("rename own", a.one("update profiles set username='Yaman2' where id=auth.uid() returning username")["username"] == "Yaman2")
ok("coins not writable", a.fails("update profiles set coins=999 where id=auth.uid()"))
ok("tag not writable", a.fails("update profiles set tag='AAAA' where id=auth.uid()"))
ok("cannot rename others", b.q("update profiles set username='Hijack' where id=%s returning 1", (a.id,)) == [])
ok("all profiles readable", len(c.q("select id from profiles")) == 3)
r = a.one("select * from create_room('00000000-0000-0000-0000-000000000000', 'Yaman2')")
code = r["code"]
ok("room host is session user", str(r["host_id"]) == a.id)
ok("own room join refused", a.fails("select join_room(%s, %s, 'x')", (code, a.id)))
r = b.one("select * from join_room(%s, '00000000-0000-0000-0000-000000000000', 'B')", (code,))
ok("guest is session user", str(r["guest_id"]) == b.id)
ok("host reads", a.one("select code from rooms where code=%s", (code,)))
ok("third cannot read", c.one("select code from rooms where code=%s", (code,)) is None)
ok("guest writes", b.q("update rooms set guest_club_id=1 where code=%s returning 1", (code,)) == [{"?column?": 1}])
ok("third cannot write", c.q("update rooms set host_score=3 where code=%s returning 1", (code,)) == [])
ok("direct insert refused", a.fails("insert into rooms (code, host_id, host_name) values ('999999', auth.uid(), 'x')"))
