import 'dart:io';

import 'package:audioplayers/audioplayers.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';
import 'package:shared_preferences/shared_preferences.dart';

/// Ayarlar (Figma 51:1088): sound and haptics, stored on the device.
///
/// Loaded once in main() before the first frame, so every reader below can
/// use the values synchronously.
class AppSettings {
  AppSettings._();
  static final AppSettings instance = AppSettings._();

  static const _soundKey = 'settings_sound';
  static const _hapticsKey = 'settings_haptics';

  final ValueNotifier<bool> sound = ValueNotifier(true);
  final ValueNotifier<bool> haptics = ValueNotifier(true);

  Future<void> load() async {
    final prefs = await SharedPreferences.getInstance();
    sound.value = prefs.getBool(_soundKey) ?? true;
    haptics.value = prefs.getBool(_hapticsKey) ?? true;
  }

  Future<void> setSound(bool on) async {
    sound.value = on;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setBool(_soundKey, on);
  }

  Future<void> setHaptics(bool on) async {
    haptics.value = on;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setBool(_hapticsKey, on);
  }
}

/// THE only way the app vibrates. Every former `HapticFeedback` call goes
/// through here, so the Titreşim switch really turns all of them off.
/// (test/haptics_test.dart fails if a raw HapticFeedback call reappears
/// anywhere under lib/ outside this file.)
class Haptics {
  Haptics._();

  static bool get _on => AppSettings.instance.haptics.value;

  static void selection() {
    if (_on) HapticFeedback.selectionClick();
  }

  static void medium() {
    if (_on) HapticFeedback.mediumImpact();
  }

  static void heavy() {
    if (_on) HapticFeedback.heavyImpact();
  }
}

/// Every sound the game makes. Each one is a file in assets/audio/ named by
/// [Sounds.assetFor]; the current files are placeholders generated by
/// tools/make_sfx.py. Replace a file with a real sound of the same name and
/// nothing in the code changes (test/sfx_assets_test.dart checks every
/// effect has its file).
enum Sfx {
  /// A letter, space or backspace on the custom keyboard.
  tap,
  correct,
  wrong,
  goal,
  roundOver,
  win,
  lose,

  /// Each beat of the 3-2-1 countdown.
  tick,
  matchFound,
}

/// THE one place sounds are played from, so the Ses switch silences all of
/// them. Short clips in low-latency mode (SoundPool on Android), mixed with
/// whatever music the player has on rather than taking audio focus.
///
/// Fire-and-forget: a sound that fails to play (no audio device, a missing
/// plugin in tests) is logged once and never surfaces to the game.
class Sounds {
  Sounds._();

  static String assetFor(Sfx sfx) => switch (sfx) {
        Sfx.tap => 'audio/tap.wav',
        Sfx.correct => 'audio/correct.wav',
        Sfx.wrong => 'audio/wrong.wav',
        Sfx.goal => 'audio/goal.wav',
        Sfx.roundOver => 'audio/round_over.wav',
        Sfx.win => 'audio/win.wav',
        Sfx.lose => 'audio/lose.wav',
        Sfx.tick => 'audio/tick.wav',
        Sfx.matchFound => 'audio/match_found.wav',
      };

  /// One player per effect, created on first use: replaying an effect
  /// restarts it instead of stacking copies (fast typing stays clean).
  static final Map<Sfx, AudioPlayer> _players = {};

  /// Set after the first platform failure, so a device without audio does
  /// not retry on every keystroke. Starts set under `flutter test`, where
  /// the audio plugin does not exist and activating its event channel
  /// would report an error into the test.
  static bool _broken = Platform.environment.containsKey('FLUTTER_TEST');

  static void play(Sfx sfx) {
    if (!AppSettings.instance.sound.value || _broken) return;
    _play(sfx).catchError((Object e) {
      _broken = true;
      debugPrint('sound disabled: $e');
    });
  }

  static Future<void> _play(Sfx sfx) async {
    var player = _players[sfx];
    if (player == null) {
      player = AudioPlayer();
      _players[sfx] = player;
      await player.setAudioContext(AudioContextConfig(
        focus: AudioContextConfigFocus.mixWithOthers,
      ).build());
      await player.setPlayerMode(PlayerMode.lowLatency);
      await player.setReleaseMode(ReleaseMode.stop);
      await player.setSource(AssetSource(assetFor(sfx)));
    } else {
      await player.stop();
    }
    await player.resume();
  }
}
